### ISSUE TITLE
copy edits for the research page

### ISSUE THREAD

**Issue by ascott** [participedia/api#429]

**Comment by jesicarson** [comment]
Participedia is guided by the research question: What kinds of participatory processes work best, for what purposes, and under what conditions? 

> Methodology [drop down]

The strategy is simple: crowdsource information on democratic innovations from around the world and then aggregate this into a public database that continually updates with new contributions. All of Participedia’s content and data is open source.

For an in-depth explanation of the history, aspirations, theory, and analytical approach of Participedia, see ‘[The Participedia Project: An Introduction’](http://archonfung.net/docs/articles/2011/FungParticipedia201112.pdf), by the two founders of Participedia, Archon Fung and Mark E. Warren.

> Data Repository [drop down]

Participedia Dataverse Repository 
 
A great deal of research on democratic innovations and participatory processes that takes place around the world is not publicly available. These materials include datasets, codebooks, statistical software syntax or scripts, dissertations, conference papers, and practitioner evaluations and reports. The Participedia Dataverse (https://dataverse.harvard.edu/dataverse/Participedia) provides a home for these materials in an accessible and organized data repository, archives the materials for long-term preservation, and generates standardized descriptions and identifiers to ease discovery and citation of the materials.
 
Researchers and practitioners can contribute to the Participedia Dataverse by depositing their research materials free of charge. Features of the Participedia data repository include:

- metrics on the number of downloads of each dataset;
- the ability to download datasets in multiple formats that are automatically generated;
- the ability to conduct data analysis right through the user interface without downloading data, since R is built into the user interface;
- long-term preservation of data;
- automatic assignment of digital object identifiers (DOIs) and other standards-compliant metadata to enable citation of datasets;
- indexing of datasets in major search engines to help users find the data;
- creation of digital fingerprints to enable authentication of datasets; and
- an open API that allows data and metadata to be used by other web services.

Please direct any questions you may have about how to contribute to Participedia Dataverse to data@participedia.net

> Surveys [drop down]

Surveys are supplementary to Participedia’s current data and narrative descriptions and are intended to gain further insight on the outcomes and effects of cases. 

The participant survey will capture the experience of participants directly involved in a participatory process. It could be delivered by organizers at the location of a particular process, or participants could be asked to complete the survey after the event. 

The observer survey will capture views pertaining to the broader impact of a particular case. ‘Observers’ include practitioners, participants or researchers with particular knowledge of that case. 

Participedia's surveys are undergoing testing, and will be available for download soon

**Comment by ascott** [comment]
included in this PR https://github.com/participedia/api/pull/434
