### ISSUE TITLE
Add file uploading to the back-end

### ISSUE THREAD

**Issue by dethe** [participedia/api#491]
For uploading `photos`, `files`, and `evaluation_reports`.

**Comment by dethe** [comment]
Front-end will upload them base-64 encoded.

**Comment by dethe** [comment]
We used to handle file uploading on the front-end, so the back-end only ever had to deal with URLs. There is something to be said for this, not using bandwidth or processing on Heroku just to be an intermediary between the browser and S3.

https://github.com/participedia/frontend/blob/master/src/utils/s3upload.js

**Comment by ascott** [comment]
With the change in architecture of the new app, I think it makes more sense to handle file uploads on the backend, since we are handling all other data validation and handling on the backend now. The code you linked to looks like it was hitting an endpoint at `/sign-s3` which would return the signed url for uploading, so we would also have to reimplement that. Rather than trying to make this existing frontend code work, I would suggest we use the [node.js aws-sdk](https://github.com/aws/aws-sdk-js) to handle uploading on the backend. In terms of performance, handling on the backend makes more sense since handling the upload on the frontend would also require more JS to be downloaded to the client. Is bandwidth or processing on the server/Heroku an issue currently?

I checked the docs/examples and it looks the aws-sdk lib makes uploading a file from an html form fairly straightforward. Here's an example: 
```
const AWS = require("aws-sdk");

const bucketName = 'participedia-uploads';
const bucketRegion = 'us-east-1';

AWS.config.update({
  region: bucketRegion
});
AWS.config.apiVersions = {
  s3: '2006-03-01',
};

const s3 = new AWS.S3();    

const file = req.body.file;
const params = {
  Bucket: bucketName,
  Key: file,
  ACL: 'public-read',
  Body: file
};

s3.putObject(params, function (err, data) {
  if (err) {
    console.log("Error: ", err);
  } else {
    console.log(data);
  }
});
```

**Comment by ascott** [comment]
pr here: https://github.com/participedia/api/pull/514
