### ISSUE TITLE
[DESIGN] admin-only field to flag 'Stub' entries

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#701]
Per conversation with @scottofletcher & @ascott implementing this feature will streamline editors process and allow them to enter more stubs on Participedia, increasing the overall quantity of content and eliminating one of the spreadsheets they currently use for tracking stub/partial entries. The feature can be combined with an admin-only search filter and tested with admins first, then we can determine the best format and language for public release (ie: separate this from search filters aesthetically, create language that gets people excited to contribute). Campaigns for use with teachers / students can be created in the future. Good goal for the fall/ spring semesters.

**Comment by ascott** [comment]
TODOs
- [ ] add checkboxes to edit form @ascott
- [ ] add data to reader view @ascott
- [ ] add attributes to search filters ui @ascott 
- [ ] DB migration to add boolean fields to cases table [stub: boolean, partial: boolean] @paninee 
- [ ] handle saving stub and partial fields in controllers/case.js @paninee 
- [ ] add stub, partial fields to search filter handling in search controller @paninee

**Comment by ascott** [comment]
@jesicarson as i'm implementing this i'm wondering if we should also add a complete flag if we are adding the partial flag. what do you think?

**Comment by jesicarson** [comment]
That seems logical. Also stub and partial are the same thing.. I just realized my description makes it sound like 2 levels of completeness. Would be good if Scott could confirm but I think having 2 values (stub/partial & complete) would be good. Unless editors need more “levels” to choose from.

**Comment by ascott** [comment]
@jesicarson @scottofletcher ah ok, i see what you mean now that stub/partial is the same thing. :)
what conditions are true for a stub entry? just a title? or only a few fields? what conditions would make a partial or complete entry?

**Comment by ascott** [comment]
@jesicarson where are you envisioning  the stub label on the reader page? i added it to the top of the data view for now. 
![Screenshot 2019-09-30 09 09 29](https://user-images.githubusercontent.com/130878/65896370-f0a21e00-e361-11e9-8cbb-f35c3583023f.png)

**Comment by jesicarson** [comment]
I hadn’t actually envisioned it on the reader page, but only as a search filter - and I’m not sure if this should be for all users or only admins... “Stub” might not be a clear term for the average person.. I need to refine the design of this system before it goes live. Let me chat with Scott today and get back to you. Thx!

**Comment by plscully** [comment]
@jesicarson @scottofletcher I've started writing about this in an attempt to figure it out. Please add your thoughts to this doc https://docs.google.com/document/d/1k_6ZswuoVm4cKmSpR-m8FisXOMq71yghsgG8lHwY4uk/edit

**Comment by jesicarson** [comment]
Decision to use the following 5 values in the admin only section, and Jesi will design to surface stubs only for now. Scott will provide the spreadsheet to alanna so she can automate the labelling of existing entries using this system. 

- Stub = entire narrative is missing OR the entry is missing enough information to constitute an entire classroom assignment's worth of work to complete
- Partial = has about 50% of its narrative OR the entry is missing enough information to constitute HALF a classroom assignment's worth of work to complete.
- Partial (citations) = an entry that is missing all citations (footnotes) but is otherwise complete (ie. would not make a good classroom assignment b/c the only things to add are references)***
- Partial (edits) = an entry that needs significant improvements to its grammar/spelling. Can be any level of completeness.
- Complete = anything above partial. Contains enough information to know what went on, and too much information to constitute half a classroom assignment.

**Comment by jesicarson** [comment]
Messing about with UI design for this on the reader... here are some thoughts. Adding the help wanted label. Thanks.

options for how to flag stubs to public on reader, and for necessary follow up - ie "request admin review" if you complete a stub. 
![Screen Shot 2019-10-03 at 1 38 45 PM](https://user-images.githubusercontent.com/13560530/66162518-4df8d200-e5e3-11e9-88db-cb3833eaadc3.png)

modal idea for stubs info icon 
![Screen Shot 2019-10-03 at 1 39 09 PM](https://user-images.githubusercontent.com/13560530/66162519-4df8d200-e5e3-11e9-9b36-8cc317151892.png)

**Comment by plscully** [comment]
Thanks @jesicarson ... I like where you're going with this

**Comment by ascott** [comment]
@jesicarson i like the idea of automatically including the prompts on the reader page depending on the completeness status. Since we would be handling this prompt on the application side, rather than including it in the body narrative, we can control the styling. what do you think of using an alert style for the prompt which could also serve as the stub/partial/citations needed label.

<img width="1680" alt="Screenshot 2019-10-05 14 24 16" src="https://user-images.githubusercontent.com/130878/66261079-1ec99880-e77c-11e9-9b3b-ac3feeaba418.png">
<img width="1680" alt="Screenshot 2019-10-05 14 25 26" src="https://user-images.githubusercontent.com/130878/66261081-20935c00-e77c-11e9-90a5-a376f81b84cf.png">

In terms of the request admin review button/functionality, my initial thought is let's how adding this completeness flag impacts the editors review flow. It may be that they don't need to be notified because if the entry has recently been edited they will see those changes and make the call to either keep or remove the stub label.

**Comment by ascott** [comment]
here's how the edit page would look with the select to choose the completeness status. i also added a very light grey background to separate the admin section from the rest of the form. let me know what you think!

<img width="889" alt="Screenshot 2019-10-05 15 22 05" src="https://user-images.githubusercontent.com/130878/66261542-25f4a480-e784-11e9-852b-5cbe80c667c6.png">
<img width="888" alt="Screenshot 2019-10-05 15 22 12" src="https://user-images.githubusercontent.com/130878/66261546-2bea8580-e784-11e9-8e41-0f3130fa5b80.png">

**Comment by scottofletcher** [comment]
@jesicarson @ascott These look great!!! Just a few notes

RE 'Request Admin-review': it all depends on whether we're going to be able to sort the homepage by last updated vs last submitted. as it stands, we will (most likely) get to any entries that have been updated recently; however, sometimes we miss them if they come in when we're doing a bunch of edits or if there is a sudden up-tick in new entries. I think giving the user some agency (and, in fact, an incentive - ie. you get to press a button to 'show off' what you accomplished!) is a good idea, especially if all it entails is sending an email to the editors. 

RE automatically including the editing prompt in the reader view: I agree that it would be optimal to do this, however, the way we have the editing prompts now is that the last few words are hyperlinked to the full-version edit screen. I don't know if it would be possible to have something like that with an auto-generated flag/alert because the url for the full-version edit is different for each entry (eg. https://www.participedia.net/case/12345/edit?full=1 -VS- https://www.participedia.net/case/54321/edit?full=1)

RE having the completeness rating above the title: I like that! would it be possible to auto-generate 'partial' as well? we could just put 'partial' for all three types and then users can see what type (citation vs edits vs regular) in the alert/editing prompt

**Comment by jesicarson** [comment]
This is great input thanks team!

1. **styling of the editing prompt** - YES - and this reminds me we have an amber-approved styling for user prompts already designed! @ascott i'll get you the design specifications for this and post here. 

2. **grey background for admin only stuff** - YES - works really well, but I suggest to darken the grey by 10% as its almost lost on my desktop screen. 

3. **request admin review** - let's keep the prompt in the popup modal with a link that sends an email to communications@participedia.net, for now, and add a button later if we feel it's necessary (that way the option exists for people to request admin review via the modal, but we're not building another element just yet).

4. **sort by** - @scottofletcher do you need sort by for your editing flow currently, or are you exporting the most recent csv in order to sort by submitted by dates?

**Comment by jesicarson** [comment]
5. **hyperlinking to entry-specific form in prompt** - @ascott is this possible? it is nice that it opens the edit form for the entry when you click the editing prompt now.

**Comment by jesicarson** [comment]
6. **including "stub" or "partial" labels on entry title** - not convinced this is a good idea, maybe STUB only, mainly so you can see at a glance of results on the homepage. @ascott what would dev time look like for something like this?

**Comment by jesicarson** [comment]
Meanwhile, for #1,  here's the editing prompt styling we had previously designed for use in forms (pulled from this issue https://github.com/participedia/frontend/issues/593#issuecomment-351516127)

![Screen Shot 2019-10-07 at 11 01 03 AM](https://user-images.githubusercontent.com/13560530/66336441-eb107f00-e8f1-11e9-96e5-844ed50faca8.png)

**Comment by ascott** [comment]
> request admin review - let's keep the prompt in the popup modal with a link that sends an email to communications@participedia.net, for now, and add a button later if we feel it's necessary (that way the option exists for people to request admin review via the modal, but we're not building another element just yet).

@jesicarson do you mean that we will just include copy in the modal asking the user to email communications@participedia.net if the stub entry is ready to be reviewed, or do you mean that we want the user to click a button and we handle sending an email automatically to communications@participedia.net. i think we should consider scoping this feature down and only include copy requesting a user send an email themselves when they would like an entry reviewed so we don't have to build custom email sending handling on the backend yet. i think we should test this feature and see how it is used before building that email notification feature.

**Comment by ascott** [comment]
> hyperlinking to entry-specific form in prompt - @ascott is this possible? it is nice that it opens the edit form for the entry when you click the editing prompt now.

yes, this is possible!

**Comment by ascott** [comment]
> including "stub" or "partial" labels on entry title - not convinced this is a good idea, maybe STUB only, mainly so you can see at a glance of results on the homepage. @ascott what would dev time look like for something like this?

this shouldn't take much time to implement, in order to label the entries on the homepage/search results page as stub entries.

**Comment by scottofletcher** [comment]
sounds good team! 

RE label on homepage/search: I don't think we need the label there - it might make things messy. can we do a mock up of it to see what it looks like? I just like it on the reader view

RE sort by drop-down: right now we're exporting the csv but that takes a loooong time because the file is so large. then we have to open it, freeze the top row, delete the 'body' column (throws off the sizing of the rows), and then sort by date uploaded. suffice it to say that we've stopped doing this on a daily basis and I've actually asked Jaskiran not to do it at all as it's a waste of time. for now we've just been trying to check in on the homepage at least 2-3 times a day and adding new entries to our tracking spreadsheet. then I download the csv when I have time and fill out any entries we missed

**Comment by ascott** [comment]
@jesicarson we don't have a sort by drop down built yet, this is something we removed back in the summer while we were working on launching. currently the articles on the home/search results page are sorted first by featured entries, and then by most recent updated at date. we only show the submitted at date on the entry card, which might be confusing since we don't use that to sort the entries on the home/search results page. here's a screen shot of with the updated at date included on my local setup to show the sorting order:

<img width="1680" alt="Screenshot 2019-10-08 12 44 18" src="https://user-images.githubusercontent.com/130878/66427888-c4be1280-e9c9-11e9-84ce-ac3599d15826.png">

what we could do if editors only want to see stub entries, is add a search filter for admin's only to return only stub entries, although i feel like this filter would be useful to all users, especially students and teachers.

**Comment by jesicarson** [comment]
Ah sorry I thought sort by was built and then removed (I thought I saw it on staging at some point), so we might have it ready to roll as needed. No biggie tho as Scott’s current work around is ok. Sounds like it’s not about seeing stubs but about seeing the most recent edits to any entry and reviewing them. This came up in a chat with the privy council as well, who may want to be notified if new edits are made to their entries (but this is another conversation). Seems like admins can live without sort by for now.

**Comment by ascott** [comment]
@jesicarson what do you think of either adding the Updated At date to the entry card, or replacing the Submitted at with the Updated at date? I feel like only having the submitted at date doesn't make it clear how the entries are sorted.

**Comment by jesicarson** [comment]
Tough call... I mean there’s another scenario where you may want to sort by how long ago a case actually took place.
Basically, I think whatever we are actually sorting by as the homepage default should be the label on the card.

**Comment by ascott** [comment]
@jesicarson ok agreed, so since we are sorting by updated date, i will replace the submitted by label/date with the updated label/date.

**Comment by jesicarson** [comment]
I think yes? Lol I never noticed it didn’t match up.

**Comment by scottofletcher** [comment]
> Sounds like it’s not about seeing stubs but about seeing the most recent edits to any entry and reviewing them.

Actually it would be much better for editors to see the most recently submitted since we're the ones editing entries (and getting displayed first). we tend to miss recent submissions because they end up on pg. 2 if we're publishing a lot of edits

**Comment by scottofletcher** [comment]
oh, also it should either by 'Updated on' or just 'Updated' (the latter is preferable since 'Submitted' is not followed by a preposition)

**Comment by ascott** [comment]
@jesicarson @paninee i added a new issue to track the development work on this and updated the title of the issue to reflect that this is discussion around the design of this feature. 
https://github.com/participedia/api/issues/765

**Comment by jesicarson** [comment]
D&T Update:
- we'll use a regular, public search filter called "Completeness" and include all 5 states
- we won't include "stub" in titles
- we will use the reader view editing prompt styling in [this comment](https://github.com/participedia/api/issues/701#issuecomment-539133938) above
- @ascott the text for the reader view editing prompts is [here](https://docs.google.com/document/d/1FUGo2__6LrOn2xOEnU1olqOQXVOa8Wm-iLwqyakc2fo/edit?usp=sharing)
- @scottofletcher needs to provide the exact text needed for each of the 5 states on the drop down menu in the entry form, and also for the search filter. Our best guess is in [alanna's mockup](https://github.com/participedia/api/issues/701#issuecomment-538694054) above.  And your detailed explanations are in [this comment](https://github.com/participedia/api/issues/701#issuecomment-537625395) above. 
---
- a separate issue should be created to deal with the correct labelling of last updated on homepage results cards. According to this comment above, sounds like it might be more useful for editors to adjust the sorting to match the current "submitted" labelling on the cards, rather than the other way around (matching the labels to the current sorting).

**Comment by plscully** [comment]
Thank you @jesicarson , this all looks good. ... @scottofletcher If you like, I'm happy to review your recommendations for text for each of the 5 states on the drop down. It's probably best to start by sharing them in G-docs while we're word-crafting.

**Comment by jesicarson** [comment]
@plscully @scottofletcher you could do your drop down text, and also review the info popup (modal text) and editing promt on reader text in [this document](https://docs.google.com/document/d/1IS2KpwfADTyzkOc3yCzIG2xPdFomS9mW__Ire4e6P04/edit#). thanks!!

**Comment by jesicarson** [comment]
@scottofletcher - as I'm drafting copy for the modal pop ups, it occurred to me that there may be scenarios when an entry can require citations / footnotes AND improvements to grammar / spelling at the same time... does that mean a case could have 2 prompts on the top? does this happen often?

**Comment by jesicarson** [comment]
@scottofletcher so you don't need to be able to assign 2 prompts at the same time, just 1 is fine?

**Comment by scottofletcher** [comment]
@jesicarson yes, when an entry has more than one issue with it (ie. citations _and_ grammar/spelling corrections needed), we leave it up to the editor's discretion to choose which prompt to assign. I tend to use the grammar/spelling prompt in these cases, since it's kind of vague (I tried to write it so it wouldn't sound pejorative since some entries w/bad grammar are entered by our ESL partners). in cases where it's a partial (less than 50% of its narrative) and has bad spelling/grammar and/or is missing citations, I just use the partial prompt (ie. 'the following entry is incomplete...etc').

**Comment by jesicarson** [comment]
i just realized why "completeness" is standing out as maybe the wrong term to use for the search filter title... because if i were to stand back and look at this, I might interpret "completeness" to mean how complete the case is (ie - is it ongoing or not), not how complete the entry about the case is. should we say "entry completeness" or "article completness" or another word? oof i'm maybe overthinking this? thx!

**Comment by scottofletcher** [comment]
oh no you're right, that is confusing. can it be 'entry completeness'?

**Comment by jesicarson** [comment]
here's quick mockup using "entry completness" - is this working?
![Screen Shot 2019-10-09 at 5 48 29 PM](https://user-images.githubusercontent.com/13560530/66530552-0ed3f080-eabd-11e9-8f8e-0d48956373ae.png)

**Comment by scottofletcher** [comment]
Looks ok to me!
