### ISSUE TITLE
Server memory issues resulting in 503's and crashes

### ISSUE THREAD

**Issue by ascott** [participedia/api#730]

**Comment by dethe** [comment]
One solution to the problem of returning HTML, but not CSS/JS is to push the CSS/JS to a separate server, such as a CDN. We'll need one more step in our deploy script to make sure the latest files are built and pushed to that server. That doesn't solve the root cause, but can reduce some of the collateral damage.

**Comment by dethe** [comment]
From about 4:30 am to 11:00 am Heroku suffered a series of major issues (https://status.heroku.com/incidents/1892) that took down many (most? all?) sites hosted there. They seemed to be returning `502 Error` which are weird ("Bad Gateway") and not found in our code at all. Our traffic passes through Cloudflare which provides some performance and protection services for us, and which converted `502 Error` to `520 Error` which isn't even a standard HTTP status code, but a Cloudflare-specific extension ("Unknown Error") and not very helpful. In short, while we could have reported back earlier about why this happened, there is not really anything we could have done to prevent or mitigate it.

**Comment by dethe** [comment]
So this one, at least, wasn't a memory issue and wasn't on us. Closing.

**Comment by ascott** [comment]
this issue was to track the 503's and server crashes and not the cloudflare 520 issue.

**Comment by ascott** [comment]
closing this in favor of more specific issues for error's that are crashing the site.
