### ISSUE TITLE
Search api needs to return # of hits-not-returned

### ISSUE THREAD

**Issue by davidascher** [participedia/api#84]
We need to be able to say "showing 30 hits out of  133" and compute the # of pages.  So we need "total_hits" added to the return payload on `/search` (and ideally all paginated endpoints)

**Comment by dethe** [comment]
OK, seems like the way to do this is to determine a cut-off point in the search weighting where we declare "this is all we'll return", select all matches with that weighting or higher as a preliminary result, then select the count and the paged results from that preliminary result.

We could do it without the weighting cut-off, but then we'll be counting increasingly irrelevant results. On the other hand, if nothing is weighted high enough we'll get zero results instead of (probably) irrelevant results. I'll get the basics in place and we can try it with different weighting cutoffs and no-cutoffs to see what feels best.
