### ISSUE TITLE
[DESIGN] Alert banner for homepage

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#904]
TBC need to discuss - when does the banner show up? can you get it back when it's closed? can it be updated by admins or hard coded by dev for now? (difference in time to launch for these variables)

possible style mockup for consideration:

![Screen Shot 2020-05-04 at 2 10 45 PM](https://user-images.githubusercontent.com/13560530/81014050-08b6b000-8e11-11ea-9324-ce2424f4c328.png)

**Comment by jesicarson** [comment]
a few notes from pat
- ok if it's only on the homepage, not all pages of the site
- yes, we'd like to allow people to close the alert (they don't need to be able to re-open it, but maybe it would re-open when you re-load the site?)

**Comment by ascott** [comment]
@jesicarson here are my notes on your questions and what i think we should do here:

> when does the banner show up? 

- on the homepage only, on every page load

> can you get it back when it's closed? 

- you can't get it back after you close it, but it will be displayed on every page load, so if you refresh the home page you will see it again. i think we could also show this alert and not offer the `x` to close it, since we are going to show it on every page load anyway, but i can go either way on this.

> can it be updated by admins or hard coded by dev for now? (difference in time to launch for these variables)

- i think we should hardcode this text by a dev for now, so that it can also be translated using phrase app. if this is text that we plan on updating really frequently then we could come up with a solution to allow an admin to change this text, but we would also have to account for how we would translate that text. once the banner is implemented, it would be a fairly quick dev task to update the text and link to something new so i don't feel like building a ui for admins to update this is necessary at this point or would make sense time wise.

**Comment by ascott** [comment]
@jesicarson i've opened a PR for this. https://github.com/participedia/api/pull/910

is this text final? if so I will run it through phrase app machine translation and update the translation files.

**Comment by jesicarson** [comment]
@ascott commented on the PR, will let @plscully take a look and give the green light to push to prod. Thanks for the quick turn around on this!!

**Comment by ascott** [comment]
- [ ] make the red bar same height as black header bar
- [ ] when alert breaks to two lines, remove button and link collection name to collection

**Comment by ascott** [comment]
@jesicarson  this is on prod now

**Comment by plscully** [comment]
@ascott @jesicarson Thank for making all of this happen on very short notice. It all looks great!

**Comment by jesicarson** [comment]
@ascott if you have time today, could you take a look at the usersnaps about the white bar of space that appears when the alert banner is closed? Thanks again for the quick turn around!

**Comment by ascott** [comment]
@jesicarson yep, i can take a look today.
